name: Egg Plant Disease
model_name: densenet121
save_path: ../models/
ckpt_path: ../models/
history_path: ../evaluation/

train_data_path: ../data/train/
test_data_path: ../data/test/
image_size: 224
classes: 7