name: Egg Plant Disease
model_name: densenet121
save_path: C:/Users/muham\Desktop/.dev/python/Projects/Egg Plant Disease/models/
ckpt_path: C:/Users/muham\Desktop/.dev/python/Projects/Egg Plant Disease/models/
history_path: C:/Users/muham\Desktop/.dev/python/Projects/Egg Plant Disease/evaluation/

train_data_path: C:/Users/muham\Desktop/.dev/python/Projects/Egg Plant Disease/data/train/
test_data_path: C:/Users/muham\Desktop/.dev/python/Projects/Egg Plant Disease/data/test/
image_size: 224
classes: 7