batch_size: 64
buffer_size: 1000
epochs: 25
val_subsplits: 5
steps_per_epoch: 0
validation_steps: 0
loss: categorical_crossentropy
optimizer: adamw
metrics: ["accuracy", "precision", "recall", "f1_score"]

